name: vobiz_webrtc
description: Modular Flutter SDK scaffold for Vobiz WebRTC on Android and iOS.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^1.0.0
