name: vobiz_demo
description: Demo app for the modular Vobiz Flutter SDK scaffold.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  vobiz_webrtc:
    path: ../../packages/vobiz_webrtc

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
